twist_mux_wall:
  ros__parameters:
    topics:
      controller:
        topic   : cmd_vel_ctrl
        timeout : 0.5
        priority: 30
      keyboard:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10
      joy:
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 20
    locks:
      error: 
        topic   : error
        timeout : 0.5
        priority: 100
